const API = "https://ytdacypygsfalkixhemj.supabase.co/functions/v1/avito-parser";
const IMPORT_API = "https://ytdacypygsfalkixhemj.supabase.co/functions/v1/avito-browser-import";
const CLEAR_API = "https://ytdacypygsfalkixhemj.supabase.co/functions/v1/avito-clear-history";
const $ = id => document.getElementById(id);
const state = { key: sessionStorage.getItem("hub-parser-key") || "", items: [], filtered: [], runId: null, historyRuns: [] };
function setStatus(text, kind = "") { $("serviceStatus").textContent = text; $("serviceStatus").className = `status-pill ${kind}`.trim(); }
function money(value) { if (value == null || Number.isNaN(Number(value))) return "—"; return new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(Number(value)) + " ₽"; }
function escapeHtml(value) { return String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
async function api(payload) { const res = await fetch(API,{method:"POST",headers:{"content-type":"application/json","x-hub-key":state.key},body:JSON.stringify(payload)}); let data={}; try{data=await res.json();}catch{} if(!res.ok){const err=new Error(data.error||`HTTP ${res.status}`);err.data=data;throw err;} return data; }
async function importApi(payload) { const res = await fetch(IMPORT_API,{method:"POST",headers:{"content-type":"application/json","x-hub-key":state.key},body:JSON.stringify(payload)}); let data={}; try{data=await res.json();}catch{} if(!res.ok) throw new Error(data.error||`HTTP ${res.status}`); return data; }
async function clearApi(payload) { const res = await fetch(CLEAR_API,{method:"POST",headers:{"content-type":"application/json","x-hub-key":state.key},body:JSON.stringify(payload)}); let data={}; try{data=await res.json();}catch{} if(!res.ok) throw new Error(data.error||`HTTP ${res.status}`); return data; }
function scoreClass(v){const n=Number(v)||0;return n>=85?"hot":n>=70?"good":n>=50?"mid":"low";}
function isUrgentFind(item){
  const score=Number(item.ai_score)||0;
  const prob=Number(item.find_probability)||0;
  const confidence=Number(item.ai_confidence)||0;
  const price=Number(item.price_value)||0;
  const marketLow=Number(item.market_price_low)||0;
  const buy=Number(item.recommended_buy_price)||0;
  const clearDiscount=price>0&&marketLow>0&&marketLow>=price*1.5;
  const buyRoom=price>0&&buy>0&&buy>=price*1.15;
  return score>=88&&prob>=75&&confidence>=60&&(clearDiscount||buyRoom);
}
function extraInfoText(item){
  if(item.info_needed) return String(item.info_needed);
  if(item.ai_risks) return String(item.ai_risks);
  return "Запросить крупные фото со всех сторон, клейма/маркировку, размеры, состояние, дефекты, происхождение вещи и подтверждение комплектности.";
}
function updateStats(){const priced=state.items.filter(x=>x.price_value!=null);const avg=priced.length?priced.reduce((s,x)=>s+Number(x.price_value),0)/priced.length:null;const best=Math.max(0,...state.items.map(x=>Number(x.ai_score)||0));$("countStat").textContent=state.items.length;$("bestStat").textContent=best?`${best}/100`:"—";$("tripStat").textContent=state.items.filter(x=>x.worth_trip).length;$("avgStat").textContent=avg==null?"—":money(avg);}
function renderItems(items=state.filtered){const body=$("resultsBody");body.innerHTML=items.map(item=>{const score=item.ai_score==null?"—":item.ai_score;const market=(item.market_price_low!=null||item.market_price_high!=null)?`${money(item.market_price_low)} — ${money(item.market_price_high)}`:"Неясно";const urgent=isUrgentFind(item);return `<article class="hunter-card ${scoreClass(score)} ${urgent?"urgent-find":""}"><div class="hunter-main">${item.image_url?`<img class="hunter-img" src="${escapeHtml(item.image_url)}" alt="" loading="lazy" referrerpolicy="no-referrer" />`:`<div class="hunter-img placeholder">A</div>`}<div class="hunter-copy">${urgent?`<div class="urgent-banner"><strong>🔥 ЯВНАЯ НАХОДКА</strong><span>СРОЧНО: сначала получить дополнительную информацию у продавца, затем покупать, если всё подтверждается.</span></div>`:""}<div class="hunter-title-row"><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.location||"")}</p></div><div class="score"><strong>${score}</strong><span>/100</span></div></div><div class="price-line"><span>Цена продавца <b>${escapeHtml(item.price_text||(item.price_value!=null?money(item.price_value):"—"))}</b></span><span>Рынок <b>${escapeHtml(market)}</b></span><span>Макс. покупка <b>${money(item.recommended_buy_price)}</b></span></div><div class="badges"><span>${escapeHtml(item.value_label||"Неясно")}</span><span>Находка ${item.find_probability==null?"—":item.find_probability+"%"}</span><span>Уверенность ${item.ai_confidence==null?"—":item.ai_confidence+"%"}</span>${urgent?`<span class="urgent-badge">СРОЧНО ПОКУПАТЬ ПОСЛЕ ПРОВЕРКИ</span>`:""}</div><div class="decision ${item.worth_trip?"yes":""}">${escapeHtml(item.decision||"Без решения")}</div>${urgent?`<div class="verify-box"><b>Перед покупкой обязательно получить:</b><p>${escapeHtml(extraInfoText(item))}</p><small>Покупать срочно только если фото, маркировка, состояние и описание подтверждают предварительную оценку.</small></div>`:""}${item.ai_reason?`<p class="reason"><b>Почему:</b> ${escapeHtml(item.ai_reason)}</p>`:""}${!urgent&&item.ai_risks?`<p class="risks"><b>Что проверить:</b> ${escapeHtml(item.ai_risks)}</p>`:""}${item.description?`<details><summary>Описание объявления</summary><p>${escapeHtml(item.description)}</p></details>`:""}<div class="hunter-actions"><a href="${escapeHtml(item.item_url)}" target="_blank" rel="noopener noreferrer">Открыть Avito ↗</a></div></div></div></article>`;}).join("");$("emptyState").classList.toggle("hidden",items.length>0);const urgentCount=items.filter(isUrgentFind).length;$("resultNote").textContent=items.length?`Показано: ${items.length}. Явных находок: ${urgentCount}. Сортировка — от лучших кандидатов.`:"Объявления не найдены.";}
function applyFilter(){const q=$("filterInput").value.trim().toLowerCase();const val=$("scoreFilter").value;const urgentOnly=val==="urgent";const min=urgentOnly?0:Number(val||0);state.filtered=state.items.filter(x=>urgentOnly?isUrgentFind(x):(Number(x.ai_score)||0)>=min).filter(x=>!q||[x.title,x.location,x.description,x.ai_reason,x.ai_risks].some(v=>String(v||"").toLowerCase().includes(q))).sort((a,b)=>{const au=isUrgentFind(a)?1:0,bu=isUrgentFind(b)?1:0;if(au!==bu)return bu-au;return (Number(b.ai_score)||0)-(Number(a.ai_score)||0)});renderItems();}
async function unlock(){const key=$("accessKey").value.trim()||state.key;if(!key)return;state.key=key;$("accessMessage").textContent="Проверяю доступ…";try{await api({action:"history"});sessionStorage.setItem("hub-parser-key",key);$("accessPanel").classList.add("hidden");$("workspace").classList.remove("hidden");$("accessMessage").textContent="";setStatus("Готов","ok");}catch(e){$("accessMessage").textContent=e.message;setStatus("Нет доступа","bad");}}
async function makeBookmarklet(){$("makeBookmarkletBtn").disabled=true;setStatus("Создаю кнопку…","busy");try{const data=await importApi({action:"create_token"});const token=data.token;const code=`javascript:(async()=>{try{const clean=t=>String(t||'').replace(/\\s+/g,' ').trim();const price=v=>{const m=String(v||'').replace(/\\s/g,'').match(/\\d+(?:[.,]\\d+)?/);return m?Number(m[0].replace(',','.')):null};const abs=u=>{try{return new URL(u,location.href).toString()}catch{return''}};const rows=[];const links=[...document.querySelectorAll('a[href*="_"]')];const seen=new Set();for(const a of links){const href=abs(a.getAttribute('href'));if(!/(^|\\.)avito\\.ru/i.test(new URL(href).hostname))continue;if(!/_\\d{5,}/.test(href))continue;const root=a.closest('[data-marker="item"],article,div[class*="iva-item"],div[class*="item"]')||a.parentElement;const title=clean(a.textContent)||clean(root?.querySelector('h3,h2,[itemprop="name"]')?.textContent);if(!title||seen.has(href))continue;seen.add(href);const text=clean(root?.textContent);const pm=text.match(/(\\d[\\d\\s]{1,12})\\s*₽/);const img=root?.querySelector('img');rows.push({external_id:(href.match(/_(\\d{5,})/)||[])[1]||'',title,price_text:pm?pm[1].trim()+' ₽':'',price_value:pm?price(pm[1]):null,location:'',item_url:href,image_url:img?abs(img.currentSrc||img.src||''):'',description:'',published_text:''});}const r=await fetch('${IMPORT_API}',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'import',token:'${token}',source_url:location.href,items:rows})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка импорта');alert('Avito → Hub: отправлено '+d.count+' объявлений. Откройте Историю в Korytnik Hub.');}catch(e){alert('Avito → Hub: '+e.message)}})();`;
const link=$("bookmarkletLink");link.href=code;link.classList.remove("hidden");$("copyBookmarkletBtn").classList.remove("hidden");$("bookmarkletHelp").classList.remove("hidden");link.dataset.code=code;setStatus("Кнопка готова","ok");}catch(e){setStatus("Ошибка","bad");$("bookmarkletHelp").classList.remove("hidden");$("bookmarkletHelp").textContent=e.message;}finally{$("makeBookmarkletBtn").disabled=false;}}
async function copyBookmarklet(){const code=$("bookmarkletLink").dataset.code||$("bookmarkletLink").href;try{await navigator.clipboard.writeText(code);setStatus("Кнопка скопирована","ok");}catch{setStatus("Не удалось скопировать","bad");}}
async function parse(){const url=$("sourceUrl").value.trim();if(!url)return;$("parseBtn").disabled=true;$("evaluateBtn").disabled=true;$("exportBtn").disabled=true;setStatus("Пробую прямой запрос…","busy");$("resultNote").textContent="Пробую получить объявления напрямую…";try{const data=await api({action:"parse",url});state.items=Array.isArray(data.items)?data.items:[];state.runId=data.run_id||null;applyFilter();updateStats();$("evaluateBtn").disabled=!state.runId||!state.items.length;$("exportBtn").disabled=!state.items.length;setStatus(data.evaluation_error?"Собрано · оценка частично":"Готово","ok");}catch(e){state.items=[];state.filtered=[];renderItems();$("resultNote").textContent=e.data?.blocked?"Avito блокирует серверный запрос. Используйте режим «Avito → Hub» ниже.":e.message;setStatus(e.data?.blocked?"Avito ограничил доступ":"Ошибка","bad");}finally{$("parseBtn").disabled=false;}}
async function evaluate(){if(!state.runId)return;$("evaluateBtn").disabled=true;setStatus("Переоцениваю…","busy");try{const data=await api({action:"evaluate",run_id:state.runId});state.items=data.items||[];applyFilter();updateStats();setStatus("Переоценено","ok");}catch(e){setStatus("Ошибка оценки","bad");$("resultNote").textContent=e.message;}finally{$("evaluateBtn").disabled=false;}}
async function showHistory(){$("historyPanel").classList.remove("hidden");$("historyList").innerHTML="Загрузка…";try{const data=await api({action:"history"});const runs=data.runs||[];state.historyRuns=runs;$("historyList").innerHTML=runs.length?runs.map(run=>`<button class="history-row" data-run="${escapeHtml(run.id)}"><span><strong>${new Date(run.created_at).toLocaleString("ru-RU")}</strong><small>${escapeHtml(run.source_url)}</small></span><span class="history-status ${escapeHtml(run.status)}">${escapeHtml(run.status)} · ${run.item_count} · best ${run.best_score??"—"}</span></button>`).join(""):"Запусков пока нет.";}catch(e){$("historyList").textContent=e.message;}}
async function clearHistory(){if(!state.historyRuns.length){$("historyList").textContent="История уже пуста.";return;}const ok=confirm("Очистить всю показанную историю запусков и связанные объявления? Это действие нельзя отменить.");if(!ok)return;$("clearHistoryBtn").disabled=true;setStatus("Очищаю историю…","busy");try{const runIds=state.historyRuns.map(x=>x.id).filter(Boolean);const data=await clearApi({confirm:"CLEAR_HISTORY",run_ids:runIds});state.historyRuns=[];state.items=[];state.filtered=[];state.runId=null;renderItems();updateStats();$("evaluateBtn").disabled=true;$("exportBtn").disabled=true;$("historyList").textContent=`История очищена. Удалено запусков: ${data.deleted_runs||0}.`;setStatus("История очищена","ok");}catch(e){setStatus("Ошибка очистки","bad");$("historyList").textContent=e.message;}finally{$("clearHistoryBtn").disabled=false;}}
async function loadRun(runId){setStatus("Загружаю историю…","busy");try{const data=await api({action:"items",run_id:runId});state.items=data.items||[];state.runId=runId;applyFilter();updateStats();$("evaluateBtn").disabled=!state.items.length;$("exportBtn").disabled=!state.items.length;$("historyPanel").classList.add("hidden");setStatus(`История · ${state.items.length}`,"ok");}catch(e){setStatus("Ошибка","bad");}}
function exportCsv(){if(!state.filtered.length)return;const cols=["title","price_text","price_value","ai_score","value_label","market_price_low","market_price_high","recommended_buy_price","find_probability","worth_trip","decision","ai_confidence","ai_reason","ai_risks","location","item_url","image_url","description","published_text"];const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv="\uFEFF"+[cols.join(";"),...state.filtered.map(x=>cols.map(c=>esc(x[c])).join(";"))].join("\r\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`konakovo_hunter_${new Date().toISOString().slice(0,19).replaceAll(":","-")}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$("unlockBtn").addEventListener("click",unlock);$("accessKey").addEventListener("keydown",e=>{if(e.key==="Enter")unlock();});$("makeBookmarkletBtn").addEventListener("click",makeBookmarklet);$("copyBookmarkletBtn").addEventListener("click",copyBookmarklet);$("parseBtn").addEventListener("click",parse);$("evaluateBtn").addEventListener("click",evaluate);$("historyBtn").addEventListener("click",showHistory);$("clearHistoryBtn").addEventListener("click",clearHistory);$("closeHistoryBtn").addEventListener("click",()=>$("historyPanel").classList.add("hidden"));$("filterInput").addEventListener("input",applyFilter);$("scoreFilter").addEventListener("change",applyFilter);$("exportBtn").addEventListener("click",exportCsv);$("historyList").addEventListener("click",e=>{const row=e.target.closest("[data-run]");if(row)loadRun(row.dataset.run);});if(state.key){$("accessKey").value=state.key;unlock();}