const SUPABASE_BASE='https://ytdacypygsfalkixhemj.supabase.co/functions/v1';
const SEARCH_ENDPOINT=SUPABASE_BASE+'/atom-b2b-search';
const SHEETS_SYNC_ENDPOINT=SUPABASE_BASE+'/atom-b2b-sheets-sync';
const state={saved:JSON.parse(localStorage.getItem('atomB2BSearchSaved')||'[]'),custom:JSON.parse(localStorage.getItem('atomB2BSearchCustom')||'[]')};
const $=id=>document.getElementById(id);
const priority=s=>s>=90?'A':s>=80?'B':'C';
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0);
const normName=v=>String(v||'').toLowerCase().replace(/[«»"'()\-–—]/g,' ').replace(/\b(пао|ао|ооо|гк|группа|компания)\b/g,' ').replace(/\s+/g,' ').trim();
const stamp=()=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()).replace(',','');
function allCompanies(){const out=[],seen=new Set();[...COMPANIES,...state.custom].forEach(c=>{const n=normName(c.name);if(n&&!seen.has(n)){seen.add(n);out.push(c);}});return out;}
function saveState(){localStorage.setItem('atomB2BSearchSaved',JSON.stringify(state.saved));localStorage.setItem('atomB2BSearchCustom',JSON.stringify(state.custom));}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(name+'View').classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='search')renderSearch();if(name==='saved')renderSaved();}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-open-search]').forEach(b=>b.onclick=()=>setView('search'));$('openSearchButton').onclick=()=>setView('search');
function renderDashboard(){const data=allCompanies();$('kpiCompanies').textContent=data.length;$('systemCompanies').textContent=data.length+' компаний';$('kpiA').textContent=data.filter(c=>c.score>=90).length;$('kpiPotential').textContent=fmt(data.reduce((s,c)=>s+(Number(c.atomMax)||0),0));$('kpiSaved').textContent=state.saved.length;$('topTargets').innerHTML=[...data].sort((a,b)=>b.score-a.score).slice(0,6).map(cardHtml).join('');}
function cardHtml(c){return `<article class="target-card"><h3>${c.name}</h3><div class="meta">${c.sector} · ${c.region||'—'}</div><div class="meta">Прогноз: <b>${fmt(c.atomMin)}–${fmt(c.atomMax)} АТОМ</b></div>${c.discovered?'<span class="custom-pill">Найдено поиском</span>':''}<div class="score-line"><span class="score-badge">${c.score}/100</span><span class="priority ${priority(c.score).toLowerCase()}">${priority(c.score)}</span></div><div class="company-actions"><button class="mini-btn" onclick='openCompany(${JSON.stringify(c.name)})'>Подробнее</button><button class="mini-btn ${state.saved.includes(c.name)?'saved':''}" onclick='toggleSaved(${JSON.stringify(c.name)})'>${state.saved.includes(c.name)?'Сохранено':'Сохранить'}</button></div></article>`}
function initFilters(){const sectors=[...new Set(allCompanies().map(c=>c.sector).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));const current=$('sectorFilter').value;$('sectorFilter').innerHTML='<option value="all">Все отрасли</option>'+sectors.map(s=>`<option>${s}</option>`).join('');if(sectors.includes(current))$('sectorFilter').value=current;$('candidateSector').innerHTML=sectors.map(s=>`<option>${s}</option>`).join('');}
function filtered(){let data=allCompanies();const q=$('companySearch').value.trim().toLowerCase(),sector=$('sectorFilter').value,minScore=+$('scoreFilter').value,minVol=+$('volumeFilter').value,pr=$('priorityFilter').value;if(q)data=data.filter(c=>[c.name,c.sector,c.use,c.why,c.region].join(' ').toLowerCase().includes(q));if(sector!=='all')data=data.filter(c=>c.sector===sector);data=data.filter(c=>(Number(c.score)||0)>=minScore&&(Number(c.atomMax)||0)>=minVol);if(pr!=='all')data=data.filter(c=>priority(c.score)===pr);const sort=$('sortFilter').value;if(sort==='score')data.sort((a,b)=>b.score-a.score||b.atomMax-a.atomMax);if(sort==='volume')data.sort((a,b)=>b.atomMax-a.atomMax||b.score-a.score);if(sort==='name')data.sort((a,b)=>a.name.localeCompare(b.name,'ru'));return data;}
function renderSearch(){const data=filtered();$('resultCount').textContent='Найдено: '+data.length;$('companiesTable').innerHTML=`<div class="company-row header"><div>Компания</div><div>Отрасль</div><div>Скоринг</div><div>Прогноз АТОМ</div><div>Сценарий</div><div></div></div>`+(data.length?data.map(c=>`<div class="company-row"><div><div class="company-name">${c.name}</div><div class="meta">${c.region||'—'}${c.discovered?' · найдено '+(c.addedAt||'') : ''}</div></div><div>${c.sector}</div><div><b>${c.score}</b> · ${priority(c.score)}</div><div>${fmt(c.atomMin)}–${fmt(c.atomMax)}</div><div>${c.use||'—'}</div><div class="company-actions"><button class="mini-btn" onclick='openCompany(${JSON.stringify(c.name)})'>Открыть</button><button class="mini-btn ${state.saved.includes(c.name)?'saved':''}" onclick='toggleSaved(${JSON.stringify(c.name)})'>★</button></div></div>`).join(''):'<div class="empty">Подходящие компании не найдены.</div>');}
['companySearch','sectorFilter','scoreFilter','volumeFilter','priorityFilter','sortFilter'].forEach(id=>$(id).addEventListener(id==='companySearch'?'input':'change',renderSearch));$('resetFilters').onclick=()=>{$('companySearch').value='';$('sectorFilter').value='all';$('scoreFilter').value='85';$('volumeFilter').value='0';$('priorityFilter').value='all';$('sortFilter').value='score';renderSearch();};
window.toggleSaved=name=>{const i=state.saved.indexOf(name);if(i>=0)state.saved.splice(i,1);else state.saved.push(name);saveState();renderDashboard();renderSearch();renderSaved();};
window.openCompany=name=>{const c=allCompanies().find(x=>x.name===name);if(!c)return;$('modalCompanyName').textContent=c.name;$('companyDetails').innerHTML=`<div class="details-grid"><div class="detail"><span>Скоринг</span><strong>${c.score}/100 · ${priority(c.score)}</strong></div><div class="detail"><span>Адресуемый парк</span><strong>${fmt(c.fleetMin)}–${fmt(c.fleetMax)}</strong></div><div class="detail"><span>Прогноз АТОМ</span><strong>${fmt(c.atomMin)}–${fmt(c.atomMax)}</strong></div><div class="detail"><span>Регион</span><strong>${c.region||'—'}</strong></div></div><div class="detail-section"><h3>Сценарий использования</h3><p>${c.use||'—'}</p></div><div class="detail-section"><h3>Почему подходит</h3><p>${c.why||'—'}</p></div><div class="detail-section"><h3>Предложение пилота</h3><p>${c.pilot||'—'}</p></div><div class="detail-section"><h3>Следующий шаг</h3><p>${c.next||'—'}</p></div>${c.source?`<div class="detail-section"><h3>Источник поиска</h3><p><a href="${c.source}" target="_blank" rel="noopener">${c.source}</a></p></div>`:''}<div class="modal-actions"><button class="primary" onclick='toggleSaved(${JSON.stringify(c.name)});closeCompany()'>${state.saved.includes(c.name)?'Убрать из shortlist':'Сохранить в shortlist'}</button></div>`;$('companyModal').classList.remove('hidden');};
window.closeCompany=()=>$('companyModal').classList.add('hidden');$('closeCompanyModal').onclick=closeCompany;$('companyModal').onclick=e=>{if(e.target===$('companyModal'))closeCompany();};
function renderSaved(){const data=state.saved.map(n=>allCompanies().find(c=>c.name===n)).filter(Boolean);$('savedCompanies').innerHTML=data.length?data.map(c=>`<article class="saved-card"><h3>${c.name}</h3><div class="meta">${c.sector} · ${c.score}/100</div><div class="meta">Прогноз: ${fmt(c.atomMin)}–${fmt(c.atomMax)} АТОМ</div><div class="company-actions"><button class="mini-btn" onclick='openCompany(${JSON.stringify(c.name)})'>Подробнее</button><button class="mini-btn" onclick='toggleSaved(${JSON.stringify(c.name)})'>Удалить</button></div></article>`).join(''):'<div class="empty">Shortlist пока пуст.</div>';}
function csv(data){const headers=['Компания','Отрасль','Регион','Парк min','Парк max','ATOM min','ATOM max','Скоринг','Сценарий','Почему подходит','Пилот','Следующий шаг','Источник','Добавлено'];const rows=data.map(c=>[c.name,c.sector,c.region,c.fleetMin,c.fleetMax,c.atomMin,c.atomMax,c.score,c.use,c.why,c.pilot,c.next,c.source||'',c.addedAt||'']);const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+[headers,...rows].map(r=>r.map(esc).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ATOM_B2B_companies.csv';a.click();URL.revokeObjectURL(a.href);}
$('exportButton').onclick=()=>csv(filtered());$('exportSavedButton').onclick=()=>csv(state.saved.map(n=>allCompanies().find(c=>c.name===n)).filter(Boolean));
function candidateScore(){const fleet=+$('candidateFleet').value,federal=+$('candidateFederal').value,parking=+$('candidateParking').value,routes=+$('candidateRoutes').value;let s=35;s+=fleet>=1000?25:fleet>=500?20:fleet>=200?14:fleet>=50?8:3;s+=federal?15:5;s+=parking?13:3;s+=routes?12:2;return Math.min(100,s);}
function preview(){const s=candidateScore();$('candidateScorePreview').textContent=`Предварительный скоринг: ${s}/100 · приоритет ${priority(s)}`;}
['candidateFleet','candidateFederal','candidateParking','candidateRoutes'].forEach(id=>$(id).addEventListener('input',preview));$('openCandidateButton').onclick=()=>{$('candidateModal').classList.remove('hidden');preview();};$('closeCandidateModal').onclick=$('cancelCandidate').onclick=()=>$('candidateModal').classList.add('hidden');$('candidateModal').onclick=e=>{if(e.target===$('candidateModal'))$('candidateModal').classList.add('hidden');};
$('candidateForm').onsubmit=e=>{e.preventDefault();const name=$('candidateName').value.trim();if(!name)return;if(allCompanies().some(c=>normName(c.name)===normName(name))){alert('Такая компания уже есть в базе.');return;}const score=candidateScore(),fleet=+$('candidateFleet').value;const item={name,sector:$('candidateSector').value,fleetMin:Math.round(fleet*.7),fleetMax:fleet,atomMin:Math.max(5,Math.round(fleet*.06)),atomMax:Math.max(10,Math.round(fleet*.12)),score,region:+$('candidateFederal').value?'Федеральный':'Региональный',use:+$('candidateRoutes').value?'Регулярные городские корпоративные маршруты':'Требуется уточнить сценарии использования',why:`Ручная оценка: парк ${fmt(fleet)}; ${+$('candidateParking').value?'есть собственная парковочная инфраструктура':'зарядную инфраструктуру нужно проверить'}.`,pilot:`Пилот ${score>=90?'15–20':score>=80?'10–15':'5–10'} АТОМ на 60–90 дней с расчётом TCO.`,next:'Найти конкретного владельца корпоративного автопарка и подтвердить размер адресуемого парка.',custom:true,addedAt:stamp()};state.custom.push(item);if(!state.saved.includes(name))state.saved.push(name);saveState();initFilters();renderDashboard();renderSearch();renderSaved();$('candidateModal').classList.add('hidden');e.target.reset();};

function injectIntegrationUI(){
 document.querySelectorAll('link[rel="icon"],link[rel="shortcut icon"]').forEach(l=>l.href='favicon.svg?v=1.1.0');
 const actions=document.querySelector('.top-actions');
 const find=document.createElement('button');find.id='findMoreButton';find.className='primary';find.textContent='Найти ещё 50';
 const sync=document.createElement('button');sync.id='syncSheetsButton';sync.className='secondary';sync.textContent='Синхронизация с Google Sheets';
 actions.prepend(sync);actions.prepend(find);
 const info=document.createElement('div');info.className='integration-meta';info.innerHTML=`<span>Последний поиск: <strong id="lastSearchAt">—</strong></span><span>Google Sheets: <strong id="lastSyncAt">не синхронизировано</strong></span><span id="integrationStatus"></span>`;
 document.querySelector('.subtitle').after(info);
 const sys=document.querySelector('.system-info');
 const rows=sys.querySelectorAll('.system-row');if(rows[0])rows[0].querySelector('strong').textContent='v1.1.0';
 const r1=document.createElement('div');r1.className='system-row';r1.innerHTML='<span>Последний поиск</span><strong id="systemLastSearch">—</strong>';
 const r2=document.createElement('div');r2.className='system-row';r2.innerHTML='<span>Google Sheets</span><strong id="systemLastSync">не было</strong>';
 sys.append(r1,r2);
 const style=document.createElement('style');style.textContent='.integration-meta{display:flex;gap:18px;flex-wrap:wrap;margin-top:11px;font-size:12px;color:#6a6f76}.integration-meta strong{color:#15171a}.integration-meta .ok{color:#198754}.integration-meta .warn{color:#a56a00}.integration-meta .error{color:#b42318}.top-actions{flex-wrap:wrap}.primary:disabled,.secondary:disabled{opacity:.55;cursor:wait}.search-new-row{background:#fbfff0}.system-row strong{text-align:right}.sync-note{font-size:11px;color:#7b8087;margin-top:6px}';document.head.append(style);
 $('findMoreButton').onclick=findMore50;$('syncSheetsButton').onclick=syncSheets;
 updateIntegrationStatus();
}
function setOpStatus(text,kind=''){$('integrationStatus').className=kind;$('integrationStatus').textContent=text;}
function updateIntegrationStatus(){const ls=localStorage.getItem('atomB2BLastSearch')||'—',sy=localStorage.getItem('atomB2BLastSync')||'не синхронизировано';if($('lastSearchAt'))$('lastSearchAt').textContent=ls;if($('systemLastSearch'))$('systemLastSearch').textContent=ls;if($('lastSyncAt'))$('lastSyncAt').textContent=sy;if($('systemLastSync'))$('systemLastSync').textContent=sy;}
async function loadServerLastSearch(){try{const r=await fetch(SEARCH_ENDPOINT,{method:'GET'});const d=await r.json();if(r.ok&&d?.latest?.searchedAt){localStorage.setItem('atomB2BLastSearch',d.latest.searchedAt);updateIntegrationStatus();}}catch(e){console.warn('last search status',e);}}
async function findMore50(){const btn=$('findMoreButton');btn.disabled=true;const old=btn.textContent;btn.textContent='Идёт поиск…';setOpStatus('Ищу новые компании в интернете и проверяю дубли…','warn');try{const existingNames=allCompanies().map(c=>c.name);const r=await fetch(SEARCH_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({existingNames})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'search_failed');const existing=new Set(allCompanies().map(c=>normName(c.name))),now=d.searchedAt||stamp();let added=0;for(const raw of d.companies||[]){const n=normName(raw.name);if(!n||existing.has(n))continue;existing.add(n);state.custom.push({...raw,discovered:true,addedAt:now});added++;}saveState();localStorage.setItem('atomB2BLastSearch',now);updateIntegrationStatus();initFilters();renderDashboard();renderSearch();setView('search');setOpStatus(added?`Найдено и добавлено новых компаний: ${added}`:'Новых уникальных компаний не найдено','ok');}catch(e){console.error(e);setOpStatus('Ошибка поиска. База не изменена.','error');}finally{btn.disabled=false;btn.textContent=old;}}
function unsyncedCompanies(){const initial=new Set(COMPANIES.map(c=>normName(c.name)));return state.custom.filter(c=>!c.syncedAt&&!initial.has(normName(c.name)));}
async function syncSheets(){const btn=$('syncSheetsButton'),rows=unsyncedCompanies();if(!rows.length){setOpStatus('Новых записей для Google Sheets нет.','ok');return;}btn.disabled=true;const old=btn.textContent;btn.textContent='Синхронизация…';setOpStatus(`Проверяю дубли перед добавлением: ${rows.length} записей…`,'warn');try{const r=await fetch(SHEETS_SYNC_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({companies:rows})});const d=await r.json();if(!r.ok||!d.ok){if(d.error==='google_write_not_configured')throw new Error('GOOGLE_NOT_CONFIGURED');throw new Error(d.error||'sync_failed');}const now=stamp();const sent=new Set(rows.map(c=>normName(c.name)));state.custom.forEach(c=>{if(sent.has(normName(c.name)))c.syncedAt=now;});saveState();localStorage.setItem('atomB2BLastSync',now);updateIntegrationStatus();setOpStatus(`Google Sheets: добавлено ${d.added||0}, дублей пропущено ${d.skipped||0}`,'ok');}catch(e){console.error(e);if(String(e.message)==='GOOGLE_NOT_CONFIGURED')setOpStatus('Канал записи Google Sheets ещё не авторизован. Данные не изменены.','error');else setOpStatus('Синхронизация не выполнена. Старые данные не изменены.','error');}finally{btn.disabled=false;btn.textContent=old;}}

initFilters();renderDashboard();renderSearch();renderSaved();injectIntegrationUI();loadServerLastSearch();
