const SHEET_ID='1v0DiMltTOFb_3SSkigH6RPXOZdEVFpIKG5XBatTCz2g';
const SHEET_NAME='TOP-50';
const SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit#gid=978672615`;
const SHEETS_WRITE_ENDPOINT='https://ytdacypygsfalkixhemj.supabase.co/functions/v1/atom-b2b-sheets-sync';
const CACHE_KEY='atomB2BSheetCacheV2';
const SYNC_KEY='atomB2BSheetLastSyncV2';
const state={saved:JSON.parse(localStorage.getItem('atomB2BSearchSaved')||'[]'),companies:[]};
const $=id=>document.getElementById(id);
const priority=s=>Number(s)>=90?'A':Number(s)>=80?'B':'C';
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0);
const normName=v=>String(v||'').toLowerCase().replace(/ё/g,'е').replace(/[«»"'()\\/\-–—]/g,' ').replace(/\b(пао|ао|ооо|гк|группа|компания)\b/g,' ').replace(/\s+/g,' ').trim();
const stamp=()=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()).replace(',','')+' МСК';
const dateStamp=()=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function normalizePhone(raw){const chunks=String(raw||'').split(/[;\n,]+/).map(v=>v.trim()).filter(Boolean),out=[];for(const chunk of chunks){let d=chunk.replace(/\D/g,'');if(d.length===11&&d[0]==='7')d='8'+d.slice(1);else if(d.length===10)d='8'+d;else if(!(d.length===11&&d[0]==='8'))continue;if(!out.includes(d))out.push(d);}return out.join(';');}
function allCompanies(){return state.companies;}
window.allCompanies=allCompanies;
function saveState(){localStorage.setItem('atomB2BSearchSaved',JSON.stringify(state.saved));}
function getCompanyLpr(c){return {found:Boolean(c),lpr:c?.lpr||'ЛПР не указан',role:c?.lprRole||'—',grade:c?.lprGrade||'—',phone:c?.phone||'',email:c?.email||''};}
window.getCompanyLpr=getCompanyLpr;
function notify(message,kind='ok'){let node=$('workflowToast');if(!node){node=document.createElement('div');node.id='workflowToast';node.className='workflow-toast';document.body.appendChild(node);}node.textContent=message;node.dataset.kind=kind;node.classList.add('show');clearTimeout(window.__atomToast);window.__atomToast=setTimeout(()=>node.classList.remove('show'),6500);}
function setStatus(id,value){const node=$(id);if(node)node.textContent=value||'—';}
function setWorkflowState(value,kind='idle'){setStatus('workflowState',value);const node=$('workflowState');if(node)node.dataset.kind=kind;}
function setButtonLoading(button,active,label){if(!button)return;if(active){if(!button.dataset.label)button.dataset.label=button.textContent;button.disabled=true;button.textContent=label;}else{button.disabled=false;button.textContent=button.dataset.label||button.textContent;}}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(name+'View')?.classList.add('active');document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='search')renderSearch();if(name==='dashboard')renderDashboard();if(name==='saved')renderSaved();}
document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-open-search]').forEach(b=>b.onclick=()=>setView('search'));
function parseNumber(cell){if(!cell)return 0;const v=cell.v;return Number(typeof v==='number'?v:String(v??cell.f??'').replace(/\s/g,'').replace(',','.'))||0;}
function cellText(cell){if(!cell)return '';const value=cell.f!=null?cell.f:cell.v;return value==null?'':String(value).trim();}
function parseSheetPayload(payload){if(!payload||payload.status==='error'||!payload.table||!Array.isArray(payload.table.rows))throw new Error('Некорректный ответ Google Таблицы');const seen=new Set(),out=[];for(const row of payload.table.rows){const c=row.c||[],name=cellText(c[1]),key=normName(name);if(!key||seen.has(key))continue;seen.add(key);out.push({
 no:parseNumber(c[0]),name,sector:cellText(c[2])||'—',fleetMin:parseNumber(c[3]),fleetMax:parseNumber(c[4]),atomMin:parseNumber(c[5]),atomMax:parseNumber(c[6]),score:parseNumber(c[7]),
 lpr:cellText(c[8])||'ЛПР не указан',lprName:cellText(c[8])||'',lprRole:cellText(c[9])||'—',lprGrade:cellText(c[10])||'—',phone:normalizePhone(cellText(c[11])),email:cellText(c[12]),social:cellText(c[13]),
 procurement:cellText(c[14]),outreach:cellText(c[15]),pilot:cellText(c[16]),why:cellText(c[17]),next:cellText(c[18]),source1:cellText(c[19]),source2:cellText(c[20]),checkedAt:cellText(c[21]),comment:cellText(c[22]),addedAt:cellText(c[23]),
 source:cellText(c[19]),contactSource:SHEET_URL,region:'',use:''
 });}return out;}
function loadGoogleSheet(){return new Promise((resolve,reject)=>{const callback=`__atomFullSheet_${Date.now()}_${Math.random().toString(36).slice(2)}`,script=document.createElement('script');let done=false,timer;const cleanup=()=>{if(done)return;done=true;clearTimeout(timer);try{delete window[callback];}catch{window[callback]=undefined;}script.remove();};const fail=e=>{cleanup();reject(e instanceof Error?e:new Error(String(e||'Ошибка Google Таблицы')));};window[callback]=payload=>{try{const rows=parseSheetPayload(payload);if(!rows.length)throw new Error('В Google Таблице нет строк');cleanup();resolve(rows);}catch(e){fail(e);}};script.async=true;script.onerror=()=>fail(new Error('Не удалось загрузить Google Таблицу'));const params=new URLSearchParams({sheet:SHEET_NAME,headers:'1',tq:'select A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X',tqx:`out:json;responseHandler:${callback}`});script.src=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?${params.toString()}`;timer=setTimeout(()=>fail(new Error('Google Таблица не ответила за 15 секунд')),15000);document.head.appendChild(script);});}
function restoreCache(){try{const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||'[]');if(Array.isArray(cached))state.companies=cached;}catch{state.companies=[];}const sync=localStorage.getItem(SYNC_KEY)||'—';setStatus('lastSyncAt',sync);setStatus('systemLastSyncAt',sync);setStatus('lastSyncResult',state.companies.length?`${state.companies.length} компаний (кэш Google Таблицы)`:'Нажмите «Синхронизировать»');}
function saveCache(){localStorage.setItem(CACHE_KEY,JSON.stringify(state.companies));}
async function syncFromGoogleSheet(options={}){if(window.__atomFullSheetPromise)return window.__atomFullSheetPromise;const button=options.button||$('syncGoogleButton');setButtonLoading(button,true,'Синхронизирую…');setWorkflowState('Читаю Google Таблицу','busy');window.__atomFullSheetPromise=(async()=>{try{const rows=await loadGoogleSheet();state.companies=rows;saveCache();const syncedAt=stamp();localStorage.setItem(SYNC_KEY,syncedAt);setStatus('lastSyncAt',syncedAt);setStatus('systemLastSyncAt',syncedAt);setStatus('lastSyncResult',`${rows.length} компаний · Google Таблица`);setStatus('systemCompanies',`${rows.length} компаний`);initFilters();renderDashboard();renderSearch();renderSaved();setWorkflowState('Синхронизировано','ok');if(!options.silent)notify(`Синхронизация завершена: загружено ${rows.length} уникальных компаний из Google Таблицы.`);return {ok:true,count:rows.length};}catch(e){console.error('Google Sheet sync',e);setWorkflowState('Ошибка синхронизации','error');setStatus('lastSyncResult',state.companies.length?`Ошибка · показан кэш ${state.companies.length} компаний`:'Ошибка загрузки Google Таблицы');if(!options.silent)notify(`Не удалось прочитать Google Таблицу. ${state.companies.length?'Оставлен последний кэш; другие источники не используются.':'Другие источники не используются.'}`,'error');return {ok:false,error:e};}finally{setButtonLoading(button,false,'');window.__atomFullSheetPromise=null;}})();return window.__atomFullSheetPromise;}
window.syncFromGoogleSheet=syncFromGoogleSheet;
function renderDashboard(){const data=allCompanies();$('kpiCompanies').textContent=data.length;$('systemCompanies').textContent=data.length?data.length+' компаний':'Google Таблица';$('kpiA').textContent=data.filter(c=>Number(c.score)>=90).length;$('kpiPotential').textContent=fmt(data.reduce((s,c)=>s+(Number(c.atomMax)||0),0));$('kpiSaved').textContent=state.saved.length;$('topTargets').innerHTML=[...data].sort((a,b)=>b.score-a.score||b.atomMax-a.atomMax).slice(0,6).map(cardHtml).join('')||'<div class="empty">Нажмите «Синхронизировать», чтобы загрузить Google Таблицу.</div>';}
function cardHtml(c){return `<article class="target-card"><h3>${esc(c.name)}</h3><div class="meta">${esc(c.sector||'—')}</div><div class="meta">Прогноз: <b>${fmt(c.atomMin)}–${fmt(c.atomMax)} АТОМ</b></div><div class="score-line"><span class="score-badge">${esc(c.score)}/100</span><span class="priority ${priority(c.score).toLowerCase()}">${priority(c.score)}</span></div><div class="company-actions"><button class="mini-btn" onclick='openCompany(${JSON.stringify(c.name)})'>Подробнее</button><button class="mini-btn ${state.saved.includes(c.name)?'saved':''}" onclick='toggleSaved(${JSON.stringify(c.name)})'>${state.saved.includes(c.name)?'Сохранено':'Сохранить'}</button></div></article>`;}
function initFilters(){const sectors=[...new Set(allCompanies().map(c=>c.sector).filter(v=>v&&v!=='—'))].sort((a,b)=>a.localeCompare(b,'ru')),current=$('sectorFilter').value;$('sectorFilter').innerHTML='<option value="all">Все отрасли</option>'+sectors.map(s=>`<option>${esc(s)}</option>`).join('');if(sectors.includes(current))$('sectorFilter').value=current;else $('sectorFilter').value='all';$('candidateSector').innerHTML=(sectors.length?sectors:['Требует классификации']).map(s=>`<option>${esc(s)}</option>`).join('');}
function filtered(){let data=[...allCompanies()];const q=$('companySearch').value.trim().toLowerCase(),sector=$('sectorFilter').value,minScore=+$('scoreFilter').value,minVol=+$('volumeFilter').value,pr=$('priorityFilter').value;if(q)data=data.filter(c=>[c.name,c.sector,c.lpr,c.lprRole,c.phone,c.email,c.procurement,c.outreach,c.why,c.comment].join(' ').toLowerCase().includes(q));if(sector!=='all')data=data.filter(c=>c.sector===sector);data=data.filter(c=>(Number(c.score)||0)>=minScore&&(Number(c.atomMax)||0)>=minVol);if(pr!=='all')data=data.filter(c=>priority(c.score)===pr);const sort=$('sortFilter').value;if(sort==='score')data.sort((a,b)=>b.score-a.score||b.atomMax-a.atomMax);if(sort==='volume')data.sort((a,b)=>b.atomMax-a.atomMax||b.score-a.score);if(sort==='name')data.sort((a,b)=>a.name.localeCompare(b.name,'ru'));return data;}
function contactHtml(c){const phone=c.phone?`<span>${esc(c.phone)}</span>`:'<span class="muted">телефон —</span>';const email=c.email?`<span>${esc(c.email)}</span>`:'<span class="muted">e-mail —</span>';return `<div class="contact-cell"><div>${phone}</div><div>${email}</div></div>`;}
function renderSearch(){const data=filtered();$('resultCount').textContent='Найдено: '+data.length;$('companiesTable').innerHTML='<div class="company-row header lpr-grid"><div>Компания</div><div>ЛПР</div><div>Телефон / e-mail</div><div>Отрасль</div><div>Скоринг</div><div>Прогноз АТОМ</div><div></div></div>'+(data.length?data.map(c=>`<div class="company-row lpr-grid"><div><div class="company-name">${esc(c.name)}</div><div class="meta">строка Google Таблицы ${esc(c.no||'—')}</div></div><div><div class="lpr-name">${esc(c.lpr||'ЛПР не указан')}</div><div class="meta">${esc(c.lprRole||'—')} · ${esc(c.lprGrade||'—')}</div></div><div>${contactHtml(c)}</div><div>${esc(c.sector||'—')}</div><div><b>${esc(c.score)}</b> · ${priority(c.score)}</div><div>${fmt(c.atomMin)}–${fmt(c.atomMax)}</div><div class="company-actions"><button class="mini-btn" onclick='openCompany(${JSON.stringify(c.name)})'>Открыть</button><button class="mini-btn ${state.saved.includes(c.name)?'saved':''}" onclick='toggleSaved(${JSON.stringify(c.name)})'>★</button></div></div>`).join(''):'<div class="empty">Нет данных. Нажмите «Синхронизировать» или измените фильтры.</div>');}
['companySearch','sectorFilter','scoreFilter','volumeFilter','priorityFilter','sortFilter'].forEach(id=>$(id).addEventListener(id==='companySearch'?'input':'change',renderSearch));$('resetFilters').onclick=()=>{$('companySearch').value='';$('sectorFilter').value='all';$('scoreFilter').value='85';$('volumeFilter').value='0';$('priorityFilter').value='all';$('sortFilter').value='score';renderSearch();};
window.toggleSaved=name=>{const i=state.saved.indexOf(name);if(i>=0)state.saved.splice(i,1);else state.saved.push(name);saveState();renderDashboard();renderSearch();renderSaved();};
window.openCompany=name=>{const c=allCompanies().find(x=>x.name===name);if(!c)return;$('modalCompanyName').textContent=c.name;$('companyDetails').innerHTML=`<div class="detail-section"><h3>ЛПР и контакты</h3><p><strong>${esc(c.lpr||'ЛПР не указан')}</strong><br>${esc(c.lprRole||'—')} · достоверность ${esc(c.lprGrade||'—')}</p><p><strong>Телефон:</strong> ${esc(c.phone||'—')}<br><strong>E-mail:</strong> ${esc(c.email||'—')}<br><strong>LinkedIn / Telegram:</strong> ${esc(c.social||'—')}</p></div><div class="details-grid"><div class="detail"><span>Скоринг</span><strong>${esc(c.score)}/100 · ${priority(c.score)}</strong></div><div class="detail"><span>Адресуемый парк</span><strong>${fmt(c.fleetMin)}–${fmt(c.fleetMax)}</strong></div><div class="detail"><span>Прогноз АТОМ</span><strong>${fmt(c.atomMin)}–${fmt(c.atomMax)}</strong></div><div class="detail"><span>Проверено</span><strong>${esc(c.checkedAt||'—')}</strong></div></div><div class="detail-section"><h3>Закупочный вход</h3><p>${esc(c.procurement||'—')}</p></div><div class="detail-section"><h3>Способ выхода</h3><p>${esc(c.outreach||'—')}</p></div><div class="detail-section"><h3>Предложение пилота</h3><p>${esc(c.pilot||'—')}</p></div><div class="detail-section"><h3>Почему подходит</h3><p>${esc(c.why||'—')}</p></div><div class="detail-section"><h3>Следующий шаг</h3><p>${esc(c.next||'—')}</p></div><div class="detail-section"><h3>Источники, записанные в Google Таблице</h3><p>${c.source1?`<a href="${esc(c.source1)}" target="_blank" rel="noopener">Источник 1</a>`:'—'}${c.source2?` · <a href="${esc(c.source2)}" target="_blank" rel="noopener">Источник 2</a>`:''}</p></div><div class="detail-section"><h3>Комментарий</h3><p>${esc(c.comment||'—')}</p><p class="meta">Добавлено: ${esc(c.addedAt||'—')}</p></div><div class="modal-actions"><a class="secondary link-button" href="${SHEET_URL}" target="_blank" rel="noopener">Открыть Google Таблицу</a><button class="primary" onclick='toggleSaved(${JSON.stringify(c.name)});closeCompany()'>${state.saved.includes(c.name)?'Убрать из shortlist':'Сохранить в shortlist'}</button></div>`;$('companyModal').classList.remove('hidden');};
window.closeCompany=()=>$('companyModal').classList.add('hidden');$('closeCompanyModal').onclick=closeCompany;$('companyModal').onclick=e=>{if(e.target===$('companyModal'))closeCompany();};
function renderSaved(){const data=state.saved.map(n=>allCompanies().find(c=>c.name===n)).filter(Boolean);$('savedCompanies').innerHTML=data.length?data.map(c=>`<article class="saved-card"><h3>${esc(c.name)}</h3><div class="meta">${esc(c.sector)} · ${esc(c.score)}/100</div><div class="meta">Прогноз: ${fmt(c.atomMin)}–${fmt(c.atomMax)} АТОМ</div><div class="company-actions"><button class="mini-btn" onclick='openCompany(${JSON.stringify(c.name)})'>Подробнее</button><button class="mini-btn" onclick='toggleSaved(${JSON.stringify(c.name)})'>Удалить</button></div></article>`).join(''):'<div class="empty">Shortlist пока пуст или сохранённые компании отсутствуют в текущей Google Таблице.</div>';}
function csv(data){const headers=['№','Компания','Отрасль','Парк min','Парк max','ATOM min','ATOM max','Скоринг','ЛПР','Должность','Достоверность ЛПР','Телефон','E-mail','LinkedIn/Telegram','Закупочный вход','Способ выхода','Пилот','Почему подходит','Следующий шаг','Источник 1','Источник 2','Проверено','Комментарий','Добавлено'];const rows=data.map(c=>[c.no,c.name,c.sector,c.fleetMin,c.fleetMax,c.atomMin,c.atomMax,c.score,c.lpr,c.lprRole,c.lprGrade,c.phone,c.email,c.social,c.procurement,c.outreach,c.pilot,c.why,c.next,c.source1,c.source2,c.checkedAt,c.comment,c.addedAt]);const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+[headers,...rows].map(r=>r.map(quote).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ATOM_B2B_GoogleSheet.csv';a.click();URL.revokeObjectURL(a.href);}
$('exportButton').onclick=()=>csv(filtered());$('exportSavedButton').onclick=()=>csv(state.saved.map(n=>allCompanies().find(c=>c.name===n)).filter(Boolean));
function candidateScore(){const fleet=+$('candidateFleet').value,federal=+$('candidateFederal').value,parking=+$('candidateParking').value,routes=+$('candidateRoutes').value;let s=35;s+=fleet>=1000?25:fleet>=500?20:fleet>=200?14:fleet>=50?8:3;s+=federal?15:5;s+=parking?13:3;s+=routes?12:2;return Math.min(100,s);}
function preview(){const s=candidateScore();$('candidateScorePreview').textContent=`Предварительный скоринг: ${s}/100 · приоритет ${priority(s)}`;}
['candidateFleet','candidateFederal','candidateParking','candidateRoutes'].forEach(id=>$(id).addEventListener('input',preview));$('openCandidateButton').onclick=()=>{$('candidateModal').classList.remove('hidden');preview();};$('closeCandidateModal').onclick=$('cancelCandidate').onclick=()=>$('candidateModal').classList.add('hidden');$('candidateModal').onclick=e=>{if(e.target===$('candidateModal'))$('candidateModal').classList.add('hidden');};
async function appendManualCompany(item){const response=await fetch(SHEETS_WRITE_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({companies:[item]})});const text=await response.text();let data={};try{data=JSON.parse(text);}catch{}if(!response.ok||!data.ok)throw new Error(data.message||data.error||`HTTP ${response.status}`);return data;}
$('candidateForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,name=$('candidateName').value.trim();if(!name)return;if(allCompanies().some(c=>normName(c.name)===normName(name))){notify('Такая компания уже есть в Google Таблице. Ничего не изменено.','same');return;}const submit=form.querySelector('button[type="submit"]'),score=candidateScore(),fleet=+$('candidateFleet').value,parking=+$('candidateParking').value,routes=+$('candidateRoutes').value;const item={name,sector:$('candidateSector').value,fleetMin:Math.round(fleet*.7),fleetMax:fleet,atomMin:Math.max(5,Math.round(fleet*.06)),atomMax:Math.max(10,Math.round(fleet*.12)),score,lprName:'',lprRole:'',lprConfidence:'C',phone:'',email:'',procurement:'',outreach:'',pilot:`Пилот ${score>=90?'15–20':score>=80?'10–15':'5–10'} АТОМ на 60–90 дней с расчётом TCO.`,why:`Ручная оценка: адресуемый парк до ${fmt(fleet)}; ${parking?'есть собственная парковочная инфраструктура':'зарядную инфраструктуру нужно проверить'}.`,next:'Уточнить ЛПР и параметры корпоративного автопарка.',source:'Ручной ввод Korytnik Hub',source1:'Ручной ввод Korytnik Hub',checkedAt:dateStamp(),comment:`Добавлено вручную. ${routes?'Регулярные городские маршруты заявлены.':'Сценарии маршрутов требуют уточнения.'}`,addedAt:stamp()};setButtonLoading(submit,true,'Добавляю…');setWorkflowState('Добавляю новую строку в Google Таблицу','busy');try{const data=await appendManualCompany(item),added=Number(data.added)||0,skipped=Number(data.skipped)||0;if(added>0){$('candidateModal').classList.add('hidden');form.reset();notify('Компания добавлена новой строкой. Старые строки не изменялись.');await syncFromGoogleSheet({silent:true});}else if(skipped>0){notify('Google Таблица обнаружила дубль. Новая строка не добавлена, старые данные не изменены.','same');await syncFromGoogleSheet({silent:true});}else{notify('Google Таблица не подтвердила добавление. Старые данные не изменены.','same');}setWorkflowState('Готово','ok');}catch(error){console.error('Manual Google append',error);setWorkflowState('Ошибка добавления','error');notify(`Не удалось добавить компанию в Google Таблицу: ${error.message}. Локально запись не создавалась.`,'error');}finally{setButtonLoading(submit,false,'');}};
$('syncGoogleButton').onclick=()=>syncFromGoogleSheet({silent:false,button:$('syncGoogleButton')});
restoreCache();initFilters();renderDashboard();renderSearch();renderSaved();setWorkflowState('Google Таблица — единственный источник','idle');setTimeout(()=>syncFromGoogleSheet({silent:true}),120);
