(function(){
'use strict';
const STAGES=[{id:'new',label:'Новая'},{id:'checked',label:'Проверена'},{id:'lpr',label:'ЛПР найден'},{id:'sheet',label:'В Google Таблице'},{id:'work',label:'В работе'}];
const STAGE_RANK=Object.fromEntries(STAGES.map((s,i)=>[s.id,i]));
const STATUS_CACHE='atomB2BCompanyStagesV1';
const ONLY_NEW_CACHE='atomB2BOnlyLatestNew';
const SEARCH_CACHE='atomB2BSearchWorkflowLastSearch';
const el=id=>document.getElementById(id);
const normalize=value=>String(value||'').toLowerCase().replace(/ё/g,'е').replace(/[«»"'()\\\-–—]/g,' ').replace(/\b(пао|ао|ооо|гк|группа|компания)\b/g,' ').replace(/\s+/g,' ').trim();
const safeJson=text=>{try{return JSON.parse(text)}catch{return {}}};
let stageMap=safeJson(localStorage.getItem(STATUS_CACHE)||'{}');
function saveStages(){localStorage.setItem(STATUS_CACHE,JSON.stringify(stageMap));}
function companyKey(v){return normalize(typeof v==='string'?v:v?.name);}
function latestSearchKeySet(){const s=safeJson(localStorage.getItem(SEARCH_CACHE)||'{}');return new Set((Array.isArray(s.names)?s.names:[]).map(normalize).filter(Boolean));}
function meaningfulLpr(v){const t=String(v||'').trim().toLowerCase();return Boolean(t&&!/нет данных|не указан|уточняется|имя публично не подтверждено/.test(t)&&t!=='—');}
function getStage(c){const k=companyKey(c);if(k&&stageMap[k])return stageMap[k];if(latestSearchKeySet().has(k))return 'new';try{if(typeof window.getCompanyLpr==='function'&&window.getCompanyLpr(c)?.found)return 'sheet';}catch(e){}if(meaningfulLpr(c?.lprName)||meaningfulLpr(c?.lpr))return 'lpr';return 'checked';}
function setStage(c,stage){const k=companyKey(c);if(!k||!(stage in STAGE_RANK))return;stageMap[k]=stage;saveStages();}
function stageOptions(current){return STAGES.map(s=>`<option value="${s.id}"${s.id===current?' selected':''}>${s.label}</option>`).join('');}
function installStyles(){if(el('pipelineStyles'))return;const style=document.createElement('style');style.id='pipelineStyles';style.textContent='.pipeline-stage-select{width:100%;min-width:118px;border:1px solid #d9dce0;border-radius:7px;background:#fff;padding:6px 7px;font-size:11px;font-weight:700}.pipeline-new-toggle{display:flex;align-items:center;gap:8px}.company-row.lpr-grid{grid-template-columns:1.08fr 1fr .72fr .95fr .58fr .42fr .55fr .72fr .42fr!important}';document.head.appendChild(style);}
function installFilters(){const grid=document.querySelector('.filters-grid');if(!grid||el('onlyLatestNewFilter'))return;const status=document.createElement('label');status.className='field';status.innerHTML=`<span>Статус</span><select id="companyStageFilter"><option value="all">Все статусы</option>${STAGES.map(s=>`<option value="${s.id}">${s.label}</option>`).join('')}</select>`;const toggle=document.createElement('label');toggle.className='pipeline-new-toggle';toggle.innerHTML='<input id="onlyLatestNewFilter" type="checkbox"><span>Только новые</span>';grid.append(status,toggle);const input=el('onlyLatestNewFilter');input.checked=localStorage.getItem(ONLY_NEW_CACHE)==='1';input.onchange=()=>{localStorage.setItem(ONLY_NEW_CACHE,input.checked?'1':'0');window.renderSearch?.();};el('companyStageFilter').onchange=()=>window.renderSearch?.();}
function decorate(){const table=el('companiesTable');if(!table)return;const latest=latestSearchKeySet();const onlyNew=Boolean(el('onlyLatestNewFilter')?.checked);const stageFilter=el('companyStageFilter')?.value||'all';let visible=0;[...table.querySelectorAll('.company-row')].forEach(row=>{if(row.classList.contains('header'))return;const name=row.querySelector('.company-name')?.textContent?.trim();if(!name)return;const company=typeof allCompanies==='function'?allCompanies().find(c=>companyKey(c)===normalize(name)):null;if(!company)return;let cell=row.querySelector('.pipeline-stage-cell');if(!cell){cell=document.createElement('div');cell.className='pipeline-stage-cell';row.insertBefore(cell,row.lastElementChild);}const stage=getStage(company);cell.innerHTML=`<select class="pipeline-stage-select">${stageOptions(stage)}</select>`;cell.querySelector('select').onchange=e=>{setStage(company,e.target.value);};const show=(!onlyNew||latest.has(companyKey(company)))&&(stageFilter==='all'||stage===stageFilter);row.hidden=!show;if(show)visible++;});const count=el('resultCount');if(count)count.textContent='Найдено: '+visible;}
function wrapRender(){if(typeof window.renderSearch!=='function'||window.renderSearch.__pipelineWrapped)return;const original=window.renderSearch;window.renderSearch=function(){original();decorate();};window.renderSearch.__pipelineWrapped=true;window.renderSearch();}
installStyles();installFilters();wrapRender();
})();