(function(){
'use strict';
const SEARCH_ENDPOINT='https://ytdacypygsfalkixhemj.supabase.co/functions/v1/atom-b2b-search';
const SHEETS_ENDPOINT='https://ytdacypygsfalkixhemj.supabase.co/functions/v1/atom-b2b-sheets-sync';
const SEARCH_CACHE='atomB2BSearchWorkflowLastSearch';
const SYNC_CACHE='atomB2BSearchWorkflowLastSync';
const el=id=>document.getElementById(id);
const normalize=value=>String(value||'').toLowerCase().replace(/ё/g,'е').replace(/[«»"'()\\\-–—]/g,' ').replace(/\b(пао|ао|ооо|гк|группа|компания)\b/g,' ').replace(/\s+/g,' ').trim();
const nowStamp=()=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()).replace(',','');
const safeJson=text=>{try{return JSON.parse(text)}catch{return {}}};
function toast(message,kind='ok'){let node=el('workflowToast');if(!node){node=document.createElement('div');node.id='workflowToast';node.className='workflow-toast';document.body.appendChild(node);}node.textContent=message;node.dataset.kind=kind;node.classList.add('show');clearTimeout(window.__atomWorkflowToast);window.__atomWorkflowToast=setTimeout(()=>node.classList.remove('show'),5200);}
function setStatus(id,value){const node=el(id);if(node)node.textContent=value||'—';}
function setWorkflowState(value,kind='idle'){setStatus('workflowState',value);const node=el('workflowState');if(node)node.dataset.kind=kind;}
function setButtonLoading(button,active,label){if(!button)return;if(active){if(!button.dataset.originalLabel)button.dataset.originalLabel=button.textContent;button.disabled=true;button.textContent=label;}else{button.disabled=false;button.textContent=button.dataset.originalLabel||button.textContent;}}
function updateCounters(){if(typeof renderDashboard==='function')renderDashboard();if(typeof initFilters==='function')initFilters();if(typeof renderSearch==='function')renderSearch();if(typeof renderSaved==='function')renderSaved();}
function mergeCompanies(items,searchedAt){if(!Array.isArray(items)||typeof state==='undefined'||!Array.isArray(state.custom))return [];const seen=new Set((typeof allCompanies==='function'?allCompanies():[]).map(c=>normalize(c.name)));const added=[];items.forEach(raw=>{const name=String(raw?.name||'').trim();const key=normalize(name);if(!key||seen.has(key))return;seen.add(key);const score=Math.max(0,Math.min(100,Number(raw.score)||0));state.custom.push({name,sector:String(raw.sector||'Требует классификации').trim(),region:String(raw.region||'Федеральный').trim(),fleetMin:Math.max(0,Number(raw.fleetMin)||0),fleetMax:Math.max(0,Number(raw.fleetMax)||0),atomMin:Math.max(0,Number(raw.atomMin)||0),atomMax:Math.max(0,Number(raw.atomMax)||0),score,use:String(raw.use||'').trim(),why:String(raw.why||'').trim(),pilot:String(raw.pilot||'').trim(),next:String(raw.next||'').trim(),source:String(raw.source||'').trim(),lprName:String(raw.lprName||'ЛПР уточняется').trim(),lprRole:String(raw.lprRole||'Fleet / Transport / Administrative / Procurement').trim(),lprConfidence:String(raw.lprConfidence||'C').trim().toUpperCase(),lprSource:String(raw.lprSource||'').trim(),discovered:true,custom:true,addedAt:searchedAt||nowStamp()});added.push(name);});if(added.length&&typeof saveState==='function')saveState();return added;}
function saveSearchStatus(payload){localStorage.setItem(SEARCH_CACHE,JSON.stringify(payload));setStatus('lastSearchAt',payload.searchedAt||'—');setStatus('systemLastSearchAt',payload.searchedAt||'—');setStatus('lastSearchResult',payload.result||'—');setStatus('systemLastSearchResult',payload.result||'—');}
function saveSyncStatus(payload){localStorage.setItem(SYNC_CACHE,JSON.stringify(payload));setStatus('lastSyncAt',payload.syncedAt||'—');setStatus('systemLastSyncAt',payload.syncedAt||'—');setStatus('lastSyncResult',payload.result||'—');}
async function runSearch(){const button=el('findMoreButton');setButtonLoading(button,true,'Ищу компании…');setWorkflowState('Идёт интернет-поиск','busy');try{const existingNames=(typeof allCompanies==='function'?allCompanies():[]).map(c=>c.name).filter(Boolean);const response=await fetch(SEARCH_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({existingNames})});const text=await response.text();const data=safeJson(text);if(!response.ok||!data.ok)throw new Error(data.error||data.message||`HTTP ${response.status}`);const searchedAt=data.searchedAt||nowStamp();const addedNames=mergeCompanies(data.companies||[],searchedAt);const added=addedNames.length;const received=Array.isArray(data.companies)?data.companies.length:0;const result=added?`+${added} новых`:(received?`${received} получено · все уже были в базе`:'Новых компаний нет');saveSearchStatus({searchedAt,result,count:added,names:addedNames});updateCounters();if(added&&el('scoreFilter'))el('scoreFilter').value='0';if(typeof renderSearch==='function')renderSearch();setWorkflowState('Поиск завершён','ok');toast(added?`Добавлено ${added} новых компаний. Проверьте и синхронизируйте с Google Таблицей.`:'Новых уникальных компаний не найдено.');}catch(error){console.error('ATOM company search',error);const searchedAt=nowStamp();saveSearchStatus({searchedAt,result:'Ошибка поиска',count:0,names:[]});setWorkflowState('Ошибка поиска','error');toast('Не удалось выполнить поиск. Серверный поиск сохранит ошибку для диагностики.','error');}finally{setButtonLoading(button,false,'');}}
function rowsForSync(){if(typeof state==='undefined'||!Array.isArray(state.custom))return [];const seen=new Set();return state.custom.filter(c=>c&&(c.discovered||c.custom)).filter(c=>{const key=normalize(c.name);if(!key||seen.has(key))return false;seen.add(key);return true;});}
async function syncToGoogle(){const button=el('syncGoogleButton');const rows=rowsForSync();if(!rows.length){toast('Нет новых локально добавленных компаний для синхронизации.','same');return;}setButtonLoading(button,true,'Синхронизирую…');setWorkflowState('Синхронизация с Google Таблицей','busy');try{const response=await fetch(SHEETS_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({companies:rows})});const text=await response.text();const data=safeJson(text);if(!response.ok||!data.ok)throw new Error(data.message||data.error||`HTTP ${response.status}`);const syncedAt=data.syncedAt?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(data.syncedAt)).replace(',',''):nowStamp();const added=Number(data.added)||0,skipped=Number(data.skipped)||0;const result=`+${added} · дублей ${skipped}`;saveSyncStatus({syncedAt,result,added,skipped,names:rows.map(c=>c.name)});setWorkflowState('Google Таблица синхронизирована','ok');toast(`Синхронизация завершена: добавлено ${added}, дублей пропущено ${skipped}. Старые строки не изменялись.`);if(typeof window.syncFromGoogleSheet==='function')await window.syncFromGoogleSheet({silent:true});updateCounters();}catch(error){console.error('ATOM Google sync',error);saveSyncStatus({syncedAt:nowStamp(),result:'Ошибка синхронизации',names:[]});setWorkflowState('Ошибка Google-синхронизации','error');toast('Не удалось синхронизировать Google Таблицу. Локальные данные сохранены и не потеряны.','error');}finally{setButtonLoading(button,false,'');}}
async function refreshServerStatus(){try{const response=await fetch(SEARCH_ENDPOINT,{method:'GET'});const text=await response.text();const data=safeJson(text);if(!response.ok||!data.ok||!data.latest)return;const cached=safeJson(localStorage.getItem(SEARCH_CACHE)||'{}');if(!cached.searchedAt){const names=Array.isArray(data.latest.companies)?data.latest.companies.map(c=>c?.name).filter(Boolean):[];saveSearchStatus({searchedAt:data.latest.searchedAt||'—',result:data.latest.status==='error'?'Последний запуск с ошибкой':`+${names.length} найдено`,count:names.length,names});}if(data.latest.status==='error')setWorkflowState('Нужен повторный поиск','error');}catch(error){console.warn('ATOM status',error);}}
function restore(){const search=safeJson(localStorage.getItem(SEARCH_CACHE)||'{}');if(search.searchedAt)saveSearchStatus(search);const sync=safeJson(localStorage.getItem(SYNC_CACHE)||'{}');if(sync.syncedAt)saveSyncStatus(sync);const contacts=localStorage.getItem('atomB2BLastContactsRefresh');if(!sync.syncedAt&&contacts){setStatus('lastSyncAt',contacts);setStatus('systemLastSyncAt',contacts);}const count=typeof allCompanies==='function'?allCompanies().length:0;const sys=el('systemCompanies');if(sys)sys.textContent=`${count} компаний`;}
function bind(){const find=el('findMoreButton');if(find)find.onclick=runSearch;const sync=el('syncGoogleButton');if(sync)sync.onclick=syncToGoogle;}
restore();bind();refreshServerStatus();
})();
