'use strict';

(() => {
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ALIASES={
    fullName:['фио','фамилия имя отчество','клиент','участник'],
    phone:['телефон','мобильный телефон','контактный телефон'],
    email:['email','e-mail','электронная почта','почта'],
    birthDate:['дата рождения','рождение'],
    birthPlace:['место рождения','месторождение'],
    drivingYears:['стаж','стаж лет','водительский стаж'],
    salutation:['обращение','пол'], messenger:['мессенджер'],
    passportSeries:['серия паспорта','паспорт серия','серия'],
    passportNumber:['номер паспорта','паспорт номер','номер'],
    passportIssuedBy:['кем выдан паспорт','кем выдан','орган выдачи паспорта'],
    passportIssueDate:['дата выдачи паспорта','паспорт дата выдачи'],
    passportCode:['код подразделения','подразделение'],
    registrationAddress:['адрес регистрации','регистрация'], actualAddress:['фактический адрес','адрес проживания'],
    driverLicense:['ву','водительское удостоверение','серия номер ву','номер ву'],
    driverLicenseIssueDate:['дата выдачи ву','ву дата выдачи'], driverCategory:['категория ву','категория'],
    driverIssuedBy:['кем выдано ву','гибдд','орган выдачи ву']
  };
  const LABELS={fullName:'ФИО',phone:'Телефон',email:'Email',birthDate:'Дата рождения',birthPlace:'Место рождения',salutation:'Обращение',registrationAddress:'Адрес регистрации',passportSeries:'Серия паспорта',passportNumber:'Номер паспорта',passportIssuedBy:'Кем выдан паспорт',passportIssueDate:'Дата выдачи паспорта',passportCode:'Код подразделения',driverLicense:'ВУ',driverLicenseIssueDate:'Дата выдачи ВУ',driverCategory:'Категория ВУ',driverIssuedBy:'Кем выдано ВУ',passportSeriesFormat:'Серия паспорта = 4 цифры',passportNumberFormat:'Номер паспорта = 6 цифр'};
  const state={rows:[],sourceName:'',selected:new Set()};

  function norm(v){return String(v??'').replace(/^\uFEFF/,'').trim().toLowerCase().replace(/ё/g,'е').replace(/№/g,'номер').replace(/[^a-zа-я0-9]+/g,'');}
  function text(v){return String(v??'').replace(/^\uFEFF/,'').trim();}
  const HEADER_MAP=(()=>{const m=new Map();Object.entries(ALIASES).forEach(([k,a])=>{a.forEach(x=>m.set(norm(x),k));m.set(norm(k),k);});return m;})();
  function normalizeDate(v){const raw=text(v);if(!raw)return'';if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;let m=/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/.exec(raw);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=/^(\d{4})[.\/](\d{1,2})[.\/](\d{1,2})$/.exec(raw);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const n=Number(raw.replace(',','.'));if(Number.isFinite(n)&&n>20000&&n<90000)return new Date(Date.UTC(1899,11,30)+Math.round(n)*86400000).toISOString().slice(0,10);return raw;}
  function parseDelimited(src0){const src=String(src0||'').replace(/^\uFEFF/,'');const first=src.split(/\r?\n/).find(x=>x.trim())||'';let delimiter=';',best=-1;[';','\t',','].forEach(d=>{const n=first.split(d).length-1;if(n>best){best=n;delimiter=d;}});const out=[];let row=[],cell='',quoted=false;for(let i=0;i<src.length;i++){const ch=src[i];if(ch==='"'){if(quoted&&src[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===delimiter&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&src[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(text))out.push(row);row=[];}else cell+=ch;}row.push(cell);if(row.some(text))out.push(row);return out;}
  function colIndex(ref){const letters=String(ref||'').match(/^[A-Z]+/i)?.[0]?.toUpperCase()||'A';let n=0;for(const ch of letters)n=n*26+ch.charCodeAt(0)-64;return Math.max(0,n-1);}
  async function unzipXlsx(file){const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer),view=new DataView(buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){eocd=i;break;}if(eocd<0)throw new Error('Не удалось прочитать XLSX: не найден ZIP-каталог.');const count=view.getUint16(eocd+10,true);let pos=view.getUint32(eocd+16,true);const decoder=new TextDecoder('utf-8'),entries=new Map();for(let i=0;i<count;i++){if(view.getUint32(pos,true)!==0x02014b50)throw new Error('Повреждён XLSX-файл.');const method=view.getUint16(pos+10,true),size=view.getUint32(pos+20,true),nl=view.getUint16(pos+28,true),el=view.getUint16(pos+30,true),cl=view.getUint16(pos+32,true),lo=view.getUint32(pos+42,true),name=decoder.decode(bytes.slice(pos+46,pos+46+nl));const lnl=view.getUint16(lo+26,true),lel=view.getUint16(lo+28,true),start=lo+30+lnl+lel;entries.set(name,{method,data:bytes.slice(start,start+size)});pos+=46+nl+el+cl;}return entries;}
  async function inflate(entry){if(!entry)return'';let out;if(entry.method===0)out=entry.data;else if(entry.method===8){if(!('DecompressionStream'in window))throw new Error('Этот браузер не умеет читать XLSX локально. Используйте CSV.');out=new Uint8Array(await new Response(new Blob([entry.data]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer());}else throw new Error('Неподдерживаемый метод сжатия XLSX.');return new TextDecoder('utf-8').decode(out);}
  async function parseXlsx(file){const entries=await unzipXlsx(file),parser=new DOMParser();let shared=[];if(entries.has('xl/sharedStrings.xml')){const x=parser.parseFromString(await inflate(entries.get('xl/sharedStrings.xml')),'application/xml');shared=[...x.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent||'').join(''));}const sheet=[...entries.keys()].filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/i.test(n)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))[0];if(!sheet)throw new Error('В XLSX не найден лист с данными.');const xml=parser.parseFromString(await inflate(entries.get(sheet)),'application/xml'),rows=[];for(const re of [...xml.getElementsByTagName('row')]){const row=[];for(const c of [...re.getElementsByTagName('c')]){const idx=colIndex(c.getAttribute('r')),type=c.getAttribute('t')||'';let v='';if(type==='inlineStr')v=[...c.getElementsByTagName('t')].map(t=>t.textContent||'').join('');else{const raw=c.getElementsByTagName('v')[0]?.textContent||'';v=type==='s'?(shared[Number(raw)]??''):raw;}row[idx]=v;}if(row.some(text))rows.push(row);}return rows;}
  function tableToRows(table){let hi=0,score=-1;for(let i=0;i<Math.min(table.length,15);i++){const s=(table[i]||[]).reduce((a,v)=>a+(HEADER_MAP.has(norm(v))?1:0),0);if(s>score){score=s;hi=i;}}if(score<4)throw new Error('Не удалось определить заголовки таблицы.');const headers=(table[hi]||[]).map(v=>HEADER_MAP.get(norm(v))||'');const out=[];table.slice(hi+1).forEach((row,i)=>{const rec={_row:hi+i+2};headers.forEach((f,j)=>{if(f)rec[f]=text(row?.[j]);});if(!Object.keys(rec).some(k=>k!=='_row'&&text(rec[k])))return;['birthDate','passportIssueDate','driverLicenseIssueDate'].forEach(k=>{if(rec[k])rec[k]=normalizeDate(rec[k]);});if(!rec.driverCategory)rec.driverCategory='B';if(rec.salutation){const n=norm(rec.salutation);if(n==='м'||n.includes('муж'))rec.salutation='Господин';else if(n==='ж'||n.includes('жен'))rec.salutation='Госпожа';}out.push(rec);});return out;}
  async function parseFile(file){const n=file.name.toLowerCase();if(n.endsWith('.xlsx'))return tableToRows(await parseXlsx(file));if(n.endsWith('.csv')||n.endsWith('.tsv')||n.endsWith('.txt'))return tableToRows(parseDelimited(await file.text()));throw new Error('Поддерживаются XLSX, CSV и TSV.');}

  function currentKinds(){return window.TestDriveDocs?.getSelected?.()||['poa','questionnaire','consent','obligation'];}
  function rowErrors(row,kinds){const req=new Set(),add=k=>req.add(k);if(kinds.includes('poa'))['fullName','passportSeries','passportNumber','passportIssuedBy','passportIssueDate','passportCode','driverLicense','driverLicenseIssueDate','driverCategory','driverIssuedBy'].forEach(add);if(kinds.includes('questionnaire'))['fullName','phone','email','passportSeries','passportNumber','passportIssuedBy','passportIssueDate','passportCode','registrationAddress'].forEach(add);if(kinds.includes('consent'))['fullName','phone','email','birthDate','salutation'].forEach(add);if(kinds.includes('obligation'))['fullName','passportSeries','passportNumber','passportIssuedBy','passportCode','birthDate','birthPlace','registrationAddress'].forEach(add);const miss=[];req.forEach(k=>{if(!text(row[k]))miss.push(k);});if(row.passportSeries&&!/^\d{4}$/.test(row.passportSeries))miss.push('passportSeriesFormat');if(row.passportNumber&&!/^\d{6}$/.test(row.passportNumber))miss.push('passportNumberFormat');return miss;}
  function mergeWithBase(row){return {...(typeof getData==='function'?getData():{}),...row};}
  function fmtDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v||'');return m?`${m[3]}.${m[2]}.${m[1]}`:(v||'');}
  function shortName(n){const p=String(n||'').trim().split(/\s+/).filter(Boolean);return p.length<2?(p[0]||''):`${p[0]} ${(p[1]?.[0]||'')}.${(p[2]?.[0]||'')}.`;}
  function dateParts(v){const months=['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v||'');return m?{day:m[3],month:months[Number(m[2])-1],year:m[1]}:{day:'____',month:'_______',year:'2026'};}
  function contextForRow(row){const d=mergeWithBase(row),ctx={...d};ctx.birthDateText=fmtDate(d.birthDate);ctx.passportIssueDateText=fmtDate(d.passportIssueDate);ctx.driverLicenseIssueDateText=fmtDate(d.driverLicenseIssueDate);ctx.companyRepPoaDateText=fmtDate(d.companyRepPoaDate);ctx.poaDateText=fmtDate(d.poaDate);const td=dateParts(d.testDriveDate||new Date().toISOString().slice(0,10));ctx.testDriveDateText=fmtDate(d.testDriveDate)||fmtDate(new Date().toISOString().slice(0,10));ctx.testDriveDateDay=td.day;ctx.testDriveDateMonth=td.month;ctx.testDriveDateYear=td.year;ctx.passportCombined=[d.passportSeries,d.passportNumber].filter(Boolean).join(' ');ctx.companyRepShort=shortName(d.companyRepName);const valid=dateParts(d.poaValidUntil);ctx.poaValidUntilDay=valid.day;ctx.poaValidUntilMonth=valid.month;ctx.poaValidUntilYear=valid.year;ctx.salutationMr=d.salutation==='Господин'?'[X]':'[ ]';ctx.salutationMs=d.salutation==='Госпожа'?'[X]':'[ ]';ctx.consentEmailMark=d.consentEmail?'[X]':'[ ]';ctx.consentSmsMark=d.consentSms?'[X]':'[ ]';ctx.consentPhoneMark=d.consentPhone?'[X]':'[ ]';ctx.consentPostMark=d.consentPost?'[X]':'[ ]';ctx.consentMessengerMark=d.consentMessenger?'[X]':'[ ]';return ctx;}
  function applyContext(clone,ctx){Object.entries(ctx).forEach(([k,v])=>{if(typeof v!=='boolean')clone.querySelectorAll(`[data-o="${k}"]`).forEach(el=>el.textContent=v||'');});}
  function selectedRows(){return state.rows.filter((_,i)=>state.selected.has(i));}

  function renderTable(){const host=$('#tdBatchTableHost'),summary=$('#tdBatchSummary'),printBtn=$('#tdBatchPrintBtn');if(!host||!summary||!printBtn)return;host.replaceChildren();if(!state.rows.length){const e=document.createElement('div');e.className='td-batch-empty';e.textContent='Загрузите XLSX или CSV. Каждая строка = один участник.';host.appendChild(e);summary.className='td-batch-summary';summary.textContent='Пакет не загружен.';printBtn.disabled=true;return;}const kinds=currentKinds(),table=document.createElement('table');table.className='td-batch-table';table.innerHTML='<thead><tr><th><input id="tdBatchAll" class="td-batch-check" type="checkbox"></th><th>Строка</th><th>ФИО</th><th>Паспорт</th><th>ВУ</th><th>Телефон / Email</th><th>Статус</th><th>Ошибки</th><th></th></tr></thead>';const body=document.createElement('tbody');let selected=0,invalid=0;state.rows.forEach((row,i)=>{const errs=rowErrors(row,kinds),valid=!errs.length;if(!valid)invalid++;if(valid&&state.selected.has(i))selected++;const tr=document.createElement('tr');if(!valid)tr.className='is-invalid';const c0=document.createElement('td'),ch=document.createElement('input');ch.type='checkbox';ch.className='td-batch-check';ch.checked=state.selected.has(i);ch.disabled=!valid;ch.onchange=()=>{ch.checked?state.selected.add(i):state.selected.delete(i);renderTable();};c0.append(ch);tr.append(c0);[String(row._row||i+2),row.fullName||'',[row.passportSeries,row.passportNumber].filter(Boolean).join(' '),row.driverLicense||'',[row.phone,row.email].filter(Boolean).join(' / '),valid?'Готово':'Ошибка',errs.map(e=>LABELS[e]||e).join(', ')].forEach((v,j)=>{const td=document.createElement('td');td.textContent=v;if(j===5)td.className=`td-batch-status ${valid?'ok':'warn'}`;if(j===6)td.className='td-batch-errors';tr.append(td);});const action=document.createElement('td');action.className='td-batch-row-actions';const b=document.createElement('button');b.type='button';b.textContent='В карточку';b.onclick=()=>loadIntoCard(row);action.append(b);tr.append(action);body.append(tr);});table.append(body);host.append(table);summary.className=`td-batch-summary ${invalid?'warn':'ok'}`;summary.textContent=`Загружено ${state.rows.length}. Готово ${state.rows.length-invalid}. С ошибками ${invalid}. Выбрано к печати ${selected}. Документы на человека: ${kinds.length}.`;printBtn.disabled=selected===0;printBtn.textContent=`Подготовить к печати (${selected} чел.)`;const all=$('#tdBatchAll');if(all){const validIdx=state.rows.map((r,i)=>({i,v:!rowErrors(r,kinds).length})).filter(x=>x.v).map(x=>x.i),sel=validIdx.filter(i=>state.selected.has(i)).length;all.checked=validIdx.length>0&&sel===validIdx.length;all.indeterminate=sel>0&&sel<validIdx.length;all.onchange=()=>{validIdx.forEach(i=>all.checked?state.selected.add(i):state.selected.delete(i));renderTable();};}}
  function loadIntoCard(row){Object.entries(row).forEach(([k,v])=>{if(k.startsWith('_'))return;const el=$(`[data-f="${k}"]`);if(!el||v==null)return;el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});}
  function downloadSample(){const content='\uFEFFФИО;Телефон;Email;Дата рождения;Место рождения;Обращение;Серия паспорта;Номер паспорта;Кем выдан паспорт;Дата выдачи паспорта;Код подразделения;Адрес регистрации;Водительское удостоверение;Дата выдачи ВУ;Категория ВУ;Кем выдано ВУ\nИванов Иван Иванович;89991234567;ivanov@example.ru;01.01.1990;г. Москва;Господин;4510;123456;ОВД района;10.10.2015;770-001;Москва;77 11 123456;15.05.2020;B;ГИБДД 7700\n';const blob=new Blob([content],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='TestDrive_Пакет_участников_образец.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function buildPrintRoot(){let root=$('#tdPrintRoot');if(!root){root=document.createElement('div');root.id='tdPrintRoot';root.setAttribute('aria-hidden','true');document.body.append(root);}else root.replaceChildren();let pages=0;const kinds=currentKinds();selectedRows().forEach(row=>{const ctx=contextForRow(row);kinds.forEach(kind=>{const source=$(`[data-doc-panel="${kind}"] .td-doc-paper`);if(!source)return;const page=source.cloneNode(true);page.classList.add('td-print-copy');page.dataset.printKind=kind;applyContext(page,ctx);root.append(page);pages++;});});return pages;}
  function printBatch(){const kinds=currentKinds();if(selectedRows().some(r=>rowErrors(r,kinds).length)){renderTable();return;}const pages=buildPrintRoot(),status=$('#tdBatchPrintStatus');if(!pages){if(status)status.textContent='Нет готовых строк для печати.';return;}if(status)status.textContent=`Подготовлено документов: ${pages}. Открываю системное окно печати...`;requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));}
  async function handleFile(file){const summary=$('#tdBatchSummary');try{summary.className='td-batch-summary';summary.textContent=`Читаю ${file.name}...`;const rows=await parseFile(file);if(!rows.length)throw new Error('В файле нет строк с участниками.');state.rows=rows;state.sourceName=file.name;state.selected.clear();const kinds=currentKinds();rows.forEach((r,i)=>{if(!rowErrors(r,kinds).length)state.selected.add(i);});renderTable();}catch(e){state.rows=[];state.selected.clear();renderTable();summary.className='td-batch-summary warn';summary.textContent=e?.message||'Не удалось прочитать файл.';}}
  function mount(){if($('#tdBatchBox'))return true;const preview=$('.preview-panel');if(!preview)return false;const box=document.createElement('section');box.id='tdBatchBox';box.className='td-batch-box';box.innerHTML=`<div class="td-batch-head"><div><strong>Массовая загрузка участников</strong><span>XLSX / CSV: одна строка = один человек. Паспорт, ВУ и данные для письменного обязательства остаются только в памяти этой вкладки.</span></div></div><div class="td-batch-actions"><label class="btn secondary td-batch-upload">Загрузить список<input id="tdBatchFile" type="file" accept=".xlsx,.csv,.tsv,.txt,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv"></label><button class="btn ghost" id="tdBatchSampleBtn" type="button">Скачать образец таблицы</button><button class="btn ghost" id="tdBatchClearBtn" type="button">Очистить пакет</button></div><div id="tdBatchSummary" class="td-batch-summary">Пакет не загружен.</div><div id="tdBatchTableHost"></div><div class="td-batch-bottom"><div class="td-batch-security">ПДн из таблицы не сохраняются в IndexedDB/localStorage и не отправляются в сеть.</div><button id="tdBatchPrintBtn" class="btn primary" type="button" disabled>Подготовить к печати</button></div><div id="tdBatchPrintStatus" class="status">Пакетная печать ещё не запускалась.</div>`;const printBox=$('#tdPrintBox');printBox?printBox.before(box):preview.querySelector('.doc-actions')?.before(box);$('#tdBatchFile').onchange=e=>{const f=e.target.files?.[0];if(f)void handleFile(f);e.target.value='';};$('#tdBatchSampleBtn').onclick=downloadSample;$('#tdBatchClearBtn').onclick=()=>{state.rows=[];state.selected.clear();renderTable();$('#tdBatchPrintStatus').textContent='Пакет очищен.';};$('#tdBatchPrintBtn').onclick=printBatch;renderTable();return true;}
  function refresh(){if(mount())renderTable();}
  window.TestDriveBatch={refresh,getRows:()=>state.rows.slice()};
  document.addEventListener('change',e=>{if(e.target?.matches?.('[data-output-doc],[data-print-doc],#tdPrintAll'))setTimeout(refresh,0);},true);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();setTimeout(mount,300);},{once:true});else{mount();setTimeout(mount,300);}
})();